### ISSUE TITLE
DEV server no longer works properly

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/web-api#168]
**Describe the bug**
When entering citizens, not all week plans are shown. Sometimes it shows the current weeks, sometimes past weeks, sometimes nothing

**To Reproduce**
1. In environments.json, set the SERVER_HOST to "https://srv.giraf.cs.aau.dk/DEV/API"
2. Run the application and enter a citizen you know to have week plans
3. Observe that it is very unstable

**Screenshots**
Martin should have lots of week plans:
![Screenshot_1603978324](https://user-images.githubusercontent.com/42242841/97580422-91468f80-19f3-11eb-970d-269504401600.png)

**Environment (please complete the following information):**
- OS: Android 10
- Emulator
- Phone: 8 Foldable API 30

**Additional context**

I get this in the console: 
```
E/flutter (30024): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (30024): Receiver: null
E/flutter (30024): Tried calling: []("data")
E/flutter (30024): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (30024): #1      WeekApi.get.<anonymous closure> (package:api_client/api/week_api.dart:35:41)
E/flutter (30024): #2      _MapStream._handleData (dart:async/stream_pipe.dart:219:31)
E/flutter (30024): #3      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
E/flutter (30024): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (30024): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (30024): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (30024): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (30024): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (30024): #9      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
E/flutter (30024): #10     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter (30024): #11     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (30024): #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (30024): #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (30024): #14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (30024): #15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (30024): #16     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
E/flutter (30024): #17     _MapStream._handleData (dart:async/stream_pipe.dart:224:10)
E/flutter (30024): #18     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
E/flutter (30024): #19     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (30024): #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (30024): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (30024): #22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (30024): #23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (30024): #24     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
E/flutter (30024): #25     _StreamController._add (dart:async/stream_controller.dart:682:7)
E/flutter (30024): #26     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:175:18)
E/flutter (30024): #27     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (30024): #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (30024): #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (30024): #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (30024): #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (30024): #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (30024): #33     Future.timeout.<anonymous closure> (dart:async/future_impl.dart:797:16)
E/flutter (30024): #34     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (30024): #35     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (30024): #36     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (30024): #37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (30024): #38     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (30024): #39     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (30024): #40     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (30024): #41     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (30024): #42     _withClient (package:http/http.dart)
E/flutter (30024): <asynchronous suspension>
E/flutter (30024): #43     get (package:http/http.dart:46:5)
E/flutter (30024): #44     HttpClient.get.<anonymous closure> (package:api_client/http/http_client.dart:52:24)
E/flutter (30024): #45     _FlatMapStreamSink.add (package:rxdart/src/transformers/flat_map.dart:18:33)
E/flutter (30024): #46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
E/flutter (30024): #47     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (30024): #48     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (30024): #49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (30024): #50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (30024): #51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (30024): #52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
E/flutter (30024): #53     _StreamController._add (dart:async/stream_controller.dart:682:7)
E/flutter (30024): #54     _StreamController.add (dart:async/stream_controller.dart:624:5)
E/flutter (30024): #55     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (30024): #56     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (30024): #57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (30024): #58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (30024): #59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (30024): #60     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
E/flutter (30024): #61     _StreamController._add (dart:async/stream_controller.dart:682:7)
E/flutter (30024): #62     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:175:18)
E/flutter (30024): #63     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (30024): #64     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (30024): #65     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (30024): #66     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (30024): #67     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (30024): #68     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (30024): #69     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (30024): #70     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (30024): #71     HttpClient._headers (package:api_client/http/http_client.dart)
E/flutter (30024): <asynchronous suspension>
E/flutter (30024): #72     HttpClient.get (package:api_client/http/http_client.dart:50:51)
E/flutter (30024): #73     WeekApi.get (package:api_client/api/week_api.dart:34:18)
E/flutter (30024): #74     WeekplansBloc.getWeekDetails (package:weekplanner/blocs/weekplan_selector_bloc.dart:135:14)
E/flutter (30024): #75     WeekplansBloc.getAllWeekInfo (package:weekplanner/blocs/weekplan_selector_bloc.dart:92:5)
E/flutter (30024): #76     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (30024): #77     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (30024): #78     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (30024): #79     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (30024): #80     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (30024): #81     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (30024): #82     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (30024): #83     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (30024): #84     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (30024): #85     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (30024): #86     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (30024): #87     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (30024): #88     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (30024): #89     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (30024): #90     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (30024): #91     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (30024): #92     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by AdrianPlesner** [comment]
This is probably related to recent changes to the database schema which have not been added to the database servers.

**Comment by AdrianPlesner** [comment]
This issue was solved by running the following SQL query directly on the giraf-dev database:
```
ALTER TABLE Activities
ADD ChoiceBoardName longtext;

UPDATE Activities
SET ChoiceBoardName = 'Choiceboard';

CREATE TABLE AlternateNames (
    Id bigint NOT NULL AUTO_INCREMENT,
    CitizenId varchar(255) CHARACTER SET utf8 NOT NULL,
    PictogramId bigint NOT NULL,
    Name longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT PK_AlternateNames PRIMARY KEY (id),
    CONSTRAINT FK_AlternateNames_AspNetUsers_CitizenId FOREIGN KEY (CitizenId) REFERENCES AspNetUsers (Id) ON DELETE CASCADE,
    CONSTRAINT FK_AlternateNames_Pictograms_PictogramId FOREIGN KEY (PictogramId) REFERENCES Pictograms (id) ON DELETE CASCADE
    );

alter table Activities add Title longtext;

with ackeynam as (select min(Pictograms.Title) as name, Activities.Key as acKey
from Pictograms, PictogramRelations, Activities
where Pictograms.id = PictogramRelations.PictogramId AND Activities.Key = PictogramRelations.ActivityId
GROUP BY Activities.Key)
update Activities
set Title = (
    select name 
    from ackeynam
    where acKey = Activities.Key
    );
```
